language: node_js
node_js: stable
install:
  - yarn
script:
  - yarn workspace example.blog build
deploy:
  provider: pages
  local-dir: ./sites/example/public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
